<?php
define("DB_HOST", "localhost");
define("DB_USER", "id3765748_bikcrum");
define("DB_PASSWORD", "test1234");
define("DB_NAME", "id3765748_firstdb");

define("INVALID_EMAIL", "INVALID_EMAIL");
define("EMAIL_NOT_FOUND", "EMAIL_NOT_FOUND");
define("INCORRECT_PASSWORD", "INCORRECT_PASSWORD");
define("EMAIL_SUSPENDED", "EMAIL_SUSPENDED");
define("LOGIN_SUCCESSFUL", "LOGIN_SUCCESSFUL");
define("EMAIL_ALREADY_EXIST", "EMAIL_ALREADY_EXIST");
define("REGISTRATION_SUCCESS", "REGISTRATION_SUCCESS");
define("REGISTRATION_ERROR", "REGISTRATION_ERROR");
?>